### ISSUE TITLE
Sonos-LCDd Crash - TypeError: Cannot read property 'protocol' of null

### ISSUE THREAD

**Issue by Rocketeer007** [Rocketeer007/sonos-lcdd#2]
Sonos-LCDd crashes when a remote script clears the queue (possibly).

```
events.js:174
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'protocol' of null
    at /home/pi/sonos-lcdd/lib/sonosLCD.js:77:37
    at Parser.<anonymous> (/home/pi/sonos-lcdd/node_modules/xml2js/lib/xml2js.js:483:18)
    at Parser.emit (events.js:198:13)
```

**Comment by Rocketeer007** [comment]
Merge Request #3 addresses this with a null-check, and adds logging so we can try and figure out what scenarios trigger this.
